### ISSUE TITLE
Could I use the models you provide to retrain my data set directly?

### ISSUE THREAD

**Issue by Alice0927** [nyukat/BIRADS_classifier#11]
Excuse me,I want to use the method of transfer learning to retrain the model you provided.Should I divide my dataset to 4 parts because there are 4 views?I don't know how to do before retrain the models.Could you give me some advice?

Thank you!
Looking forward to your reply!

**Comment by kjgeras** [comment]
Hi Alice,

If you only have one image per example (as opposed to four), you should only use one column from our network.
