### ISSUE TITLE
Image normalization

### ISSUE THREAD

**Issue by abrichr** [nyukat/BIRADS_classifier#15]
Hello,

Thank you for making this code available!

My question is regarding data preprocessing. I noticed that the example images you provide in the `images` directory have values in the range 0 - 255. Is this how you scaled the training images? Other than the whitening mentioned in the paper (subtracting the mean and dividing by the standard deviation), what other preprocessing did you apply during training and inference (e.g. adaptive histogram equalization)? 

Thanks,
-Richard

**Comment by jpatrickpark** [comment]
During training and inference, we directly standardized original 12-bit integer values without rescaling the images to 0-255 range. The images have values typically in the 0-4095 range. We did not apply any preprocessing that is not mentioned in the paper. Depending on the manufacturer, their proprietary preprocessing algorithms may have been applied in the images.

**Comment by abrichr** [comment]
Thank you for the quick response! Regarding the following:

> The images have values typically in the 0-4095 range.

Can you please clarify: does this mean that some images had values outside this range? If so, do you know approximately how many, and in which ranges?

**Comment by jpatrickpark** [comment]
If I remember correctly, all valid mammograms we have were within the 0-4095 range.
