### ISSUE TITLE
Source code 

### ISSUE THREAD

**Issue by alex83803** [nyukat/BIRADS_classifier#3]
Dear Krzysztof, 

we are working on a similar projet and struggle using high resolution pictures in our neuronal network. 
as we understand, you have managed to bypass this problem and explain the way you did it in your paper. What an amazing job!

Is there a chance that you share your source code with us in order for us to understand how you have implemented the concept in your code.

We would be more than greatful :-).

We are looking forward to read from you,

**Comment by kjgeras** [comment]
The code of the model is in the repository. Please start from this file:
https://github.com/nyukat/BIRADS_classifier/blob/master/models_tf.py
